; ═══════════════════════════════════════════════════
; Generated by Arabic Mathematical Language Compiler
; الدستور: ﴿كتاب أحكمت آياته﴾
; ═══════════════════════════════════════════════════

global _start

section .bss
    arena_ptr resq 1
    arena_mem resb 262144
    file_buf resb 4096
    vars resb 1024
    num_buf resb 32

section .data
    newline db 10
    minus_str db '-'
    str_1 db 216, 167, 216, 174, 216, 170, 216, 168, 216, 167, 216, 177, 32, 216, 168, 216, 185, 216, 175, 32, 216, 167, 217, 132, 216, 170, 216, 173, 216, 175, 217, 138, 216, 171
    str_1_len equ $ - str_1

section .text

arena_alloc:
    push rdi
    mov rax, [arena_ptr]
    test rax, rax
    jnz .arena_init
    mov rax, arena_mem
    mov [arena_ptr], rax
.arena_init:
    mov rdx, rax
    add rdx, rdi
    mov [arena_ptr], rdx
    pop rdi
    ret

print_int:
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    test rax, rax
    jns .pi_pos
    neg rax
    push rax
    mov rax, 1
    mov rdi, 1
    lea rsi, [minus_str]
    mov rdx, 1
    syscall
    pop rax
.pi_pos:
    mov rbx, 10
    mov rcx, 0
    lea rdi, [num_buf + 31]
.piloop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rdi
    mov [rdi], dl
    inc rcx
    test rax, rax
    jnz .piloop
    mov rsi, rdi
    mov byte [rsi + rcx], 10
    inc rcx
    mov rdi, 1
    mov rax, 1
    mov rdx, rcx
    syscall
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    ret

_start:
    mov qword [arena_ptr], 0

    mov rdi, 42
    call arena_alloc
    mov qword [rax], 34
    lea rsi, [str_1]
    lea rdi, [rax + 8]
    mov rcx, 34
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 100
    mov [vars + 0], rax
    mov rax, [vars + 0]
    call print_int

    mov rax, 60
    xor rdi, rdi
    syscall
