; ═══════════════════════════════════════════════════
; Generated by Arabic Mathematical Language Compiler
; الدستور: ﴿كتاب أحكمت آياته﴾
; ═══════════════════════════════════════════════════

global _start

section .bss
    arena_ptr resq 1
    arena_mem resb 262144
    file_buf resb 4096
    vars resb 1024
    num_buf resb 32

section .data
    newline db 10
    minus_str db '-'
    str_1 db 61, 61, 61, 32, 217, 133, 216, 173, 216, 175, 216, 175, 32, 217, 133, 216, 181, 217, 129, 217, 136, 217, 129, 216, 169, 32, 50, 195, 151, 50, 32, 61, 61, 61
    str_1_len equ $ - str_1
    str_2 db 100, 101, 116, 40, 91, 49, 44, 50, 59, 51, 44, 52, 93, 41, 32, 61, 32
    str_2_len equ $ - str_2
    str_3 db 61, 61, 61, 32, 216, 172, 217, 133, 216, 185, 32, 217, 133, 216, 181, 217, 129, 217, 136, 217, 129, 216, 170, 217, 138, 217, 134, 32, 61, 61, 61
    str_3_len equ $ - str_3
    str_4 db 91, 49, 44, 50, 59, 51, 44, 52, 93, 32, 43, 32, 91, 53, 44, 54, 59, 55, 44, 56, 93, 32, 61
    str_4_len equ $ - str_4
    str_5 db 32, 32, 32, 91
    str_5_len equ $ - str_5
    str_6 db 32, 32, 32, 59
    str_6_len equ $ - str_6
    str_7 db 32, 32, 32, 93
    str_7_len equ $ - str_7
    str_8 db 61, 61, 61, 32, 216, 182, 216, 177, 216, 168, 32, 217, 129, 217, 138, 32, 216, 185, 216, 175, 216, 175, 32, 61, 61, 61
    str_8_len equ $ - str_8
    str_9 db 51, 32, 195, 151, 32, 91, 49, 44, 50, 59, 51, 44, 52, 93, 32, 61
    str_9_len equ $ - str_9
    str_10 db 61, 61, 61, 32, 216, 167, 217, 132, 217, 133, 217, 134, 217, 130, 217, 136, 217, 132, 32, 61, 61, 61
    str_10_len equ $ - str_10
    str_11 db 91, 49, 44, 50, 59, 51, 44, 52, 93, 94, 84, 32, 61
    str_11_len equ $ - str_11

section .text

arena_alloc:
    push rdi
    mov rax, [arena_ptr]
    test rax, rax
    jnz .arena_init
    mov rax, arena_mem
    mov [arena_ptr], rax
.arena_init:
    mov rdx, rax
    add rdx, rdi
    mov [arena_ptr], rdx
    pop rdi
    ret

print_int:
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    test rax, rax
    jns .pi_pos
    neg rax
    push rax
    mov rax, 1
    mov rdi, 1
    lea rsi, [minus_str]
    mov rdx, 1
    syscall
    pop rax
.pi_pos:
    mov rbx, 10
    mov rcx, 0
    lea rdi, [num_buf + 31]
.piloop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rdi
    mov [rdi], dl
    inc rcx
    test rax, rax
    jnz .piloop
    mov rsi, rdi
    mov byte [rsi + rcx], 10
    inc rcx
    mov rdi, 1
    mov rax, 1
    mov rdx, rcx
    syscall
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    ret

_start:
    mov qword [arena_ptr], 0

    mov rdi, 42
    call arena_alloc
    mov qword [rax], 34
    lea rsi, [str_1]
    lea rdi, [rax + 8]
    mov rcx, 34
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 1
    mov [vars + 0], rax
    mov rax, 2
    mov [vars + 8], rax
    mov rax, 3
    mov [vars + 16], rax
    mov rax, 4
    mov [vars + 24], rax
    mov rax, [vars + 0]
    push rax
    mov rax, [vars + 24]
    mov rbx, rax
    pop rax
    imul rax, rbx
    push rax
    mov rax, [vars + 8]
    push rax
    mov rax, [vars + 16]
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov rbx, rax
    pop rax
    sub rax, rbx
    mov [vars + 32], rax
    mov rdi, 25
    call arena_alloc
    mov qword [rax], 17
    lea rsi, [str_2]
    lea rdi, [rax + 8]
    mov rcx, 17
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 32]
    call print_int
    mov rdi, 39
    call arena_alloc
    mov qword [rax], 31
    lea rsi, [str_3]
    lea rdi, [rax + 8]
    mov rcx, 31
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 1
    mov [vars + 40], rax
    mov rax, 2
    mov [vars + 48], rax
    mov rax, 3
    mov [vars + 56], rax
    mov rax, 4
    mov [vars + 64], rax
    mov rax, 5
    mov [vars + 72], rax
    mov rax, 6
    mov [vars + 80], rax
    mov rax, 7
    mov [vars + 88], rax
    mov rax, 8
    mov [vars + 96], rax
    mov rax, [vars + 40]
    push rax
    mov rax, [vars + 72]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 104], rax
    mov rax, [vars + 48]
    push rax
    mov rax, [vars + 80]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 112], rax
    mov rax, [vars + 56]
    push rax
    mov rax, [vars + 88]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 120], rax
    mov rax, [vars + 64]
    push rax
    mov rax, [vars + 96]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 128], rax
    mov rdi, 31
    call arena_alloc
    mov qword [rax], 23
    lea rsi, [str_4]
    lea rdi, [rax + 8]
    mov rcx, 23
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 12
    call arena_alloc
    mov qword [rax], 4
    lea rsi, [str_5]
    lea rdi, [rax + 8]
    mov rcx, 4
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 104]
    call print_int
    mov rax, [vars + 112]
    call print_int
    mov rdi, 12
    call arena_alloc
    mov qword [rax], 4
    lea rsi, [str_6]
    lea rdi, [rax + 8]
    mov rcx, 4
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 120]
    call print_int
    mov rax, [vars + 128]
    call print_int
    mov rdi, 12
    call arena_alloc
    mov qword [rax], 4
    lea rsi, [str_7]
    lea rdi, [rax + 8]
    mov rcx, 4
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 34
    call arena_alloc
    mov qword [rax], 26
    lea rsi, [str_8]
    lea rdi, [rax + 8]
    mov rcx, 26
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 3
    mov [vars + 136], rax
    mov rax, [vars + 40]
    push rax
    mov rax, [vars + 136]
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov [vars + 144], rax
    mov rax, [vars + 48]
    push rax
    mov rax, [vars + 136]
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov [vars + 152], rax
    mov rax, [vars + 56]
    push rax
    mov rax, [vars + 136]
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov [vars + 160], rax
    mov rax, [vars + 64]
    push rax
    mov rax, [vars + 136]
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov [vars + 168], rax
    mov rdi, 24
    call arena_alloc
    mov qword [rax], 16
    lea rsi, [str_9]
    lea rdi, [rax + 8]
    mov rcx, 16
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 144]
    call print_int
    mov rax, [vars + 152]
    call print_int
    mov rax, [vars + 160]
    call print_int
    mov rax, [vars + 168]
    call print_int
    mov rdi, 30
    call arena_alloc
    mov qword [rax], 22
    lea rsi, [str_10]
    lea rdi, [rax + 8]
    mov rcx, 22
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 21
    call arena_alloc
    mov qword [rax], 13
    lea rsi, [str_11]
    lea rdi, [rax + 8]
    mov rcx, 13
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 0]
    call print_int
    mov rax, [vars + 16]
    call print_int
    mov rax, [vars + 8]
    call print_int
    mov rax, [vars + 24]
    call print_int

    mov rax, 60
    xor rdi, rdi
    syscall
