; ═══════════════════════════════════════════════════
; Generated by Arabic Mathematical Language Compiler
; الدستور: ﴿كتاب أحكمت آياته﴾
; ═══════════════════════════════════════════════════

global _start

section .bss
    arena_ptr resq 1
    arena_mem resb 262144
    file_buf resb 4096
    vars resb 1024
    num_buf resb 32

section .data
    newline db 10
    minus_str db '-'
    str_1 db 226, 149, 148, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 151
    str_1_len equ $ - str_1
    str_2 db 226, 149, 145, 32, 32, 32, 32, 32, 32, 32, 32, 32, 216, 167, 217, 132, 216, 172, 217, 133, 216, 185, 32, 216, 167, 217, 132, 217, 133, 216, 170, 217, 136, 216, 167, 216, 178, 217, 138, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 226, 149, 145
    str_2_len equ $ - str_2
    str_3 db 226, 149, 154, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 157
    str_3_len equ $ - str_3
    str_4 db 
    str_4_len equ $ - str_4
    str_5 db 216, 167, 217, 132, 217, 133, 216, 180, 217, 131, 217, 132, 216, 169, 58, 32, 217, 133, 216, 172, 217, 133, 217, 136, 216, 185, 32, 49, 32, 216, 165, 217, 132, 217, 137, 32, 49, 48, 48
    str_5_len equ $ - str_5
    str_6 db 216, 167, 217, 132, 216, 173, 217, 132, 32, 216, 167, 217, 132, 217, 133, 216, 170, 216, 179, 217, 132, 216, 179, 217, 132, 58
    str_6_len equ $ - str_6
    str_7 db 216, 167, 217, 132, 217, 134, 216, 170, 217, 138, 216, 172, 216, 169, 58, 32
    str_7_len equ $ - str_7
    str_8 db 216, 167, 217, 132, 217, 133, 216, 170, 217, 136, 217, 130, 216, 185, 58, 32, 53, 48, 53, 48
    str_8_len equ $ - str_8
    str_9 db 
    str_9_len equ $ - str_9
    str_10 db 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144
    str_10_len equ $ - str_10
    str_11 db 216, 167, 217, 132, 216, 173, 217, 132, 32, 216, 167, 217, 132, 217, 133, 216, 170, 217, 136, 216, 167, 216, 178, 217, 138, 58, 32, 52, 32, 216, 174, 217, 138, 217, 136, 216, 183
    str_11_len equ $ - str_11
    str_12 db 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144
    str_12_len equ $ - str_12
    str_13 db 
    str_13_len equ $ - str_13
    str_14 db 240, 159, 147, 141, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 49, 58, 32, 217, 133, 216, 172, 217, 133, 217, 136, 216, 185, 32, 49, 32, 216, 165, 217, 132, 217, 137, 32, 50, 53
    str_14_len equ $ - str_14
    str_15 db 32, 32, 216, 167, 217, 132, 217, 134, 216, 170, 217, 138, 216, 172, 216, 169, 58, 32
    str_15_len equ $ - str_15
    str_16 db 
    str_16_len equ $ - str_16
    str_17 db 240, 159, 147, 141, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 50, 58, 32, 217, 133, 216, 172, 217, 133, 217, 136, 216, 185, 32, 50, 54, 32, 216, 165, 217, 132, 217, 137, 32, 53, 48
    str_17_len equ $ - str_17
    str_18 db 32, 32, 216, 167, 217, 132, 217, 134, 216, 170, 217, 138, 216, 172, 216, 169, 58, 32
    str_18_len equ $ - str_18
    str_19 db 
    str_19_len equ $ - str_19
    str_20 db 240, 159, 147, 141, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 51, 58, 32, 217, 133, 216, 172, 217, 133, 217, 136, 216, 185, 32, 53, 49, 32, 216, 165, 217, 132, 217, 137, 32, 55, 53
    str_20_len equ $ - str_20
    str_21 db 32, 32, 216, 167, 217, 132, 217, 134, 216, 170, 217, 138, 216, 172, 216, 169, 58, 32
    str_21_len equ $ - str_21
    str_22 db 
    str_22_len equ $ - str_22
    str_23 db 240, 159, 147, 141, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 52, 58, 32, 217, 133, 216, 172, 217, 133, 217, 136, 216, 185, 32, 55, 54, 32, 216, 165, 217, 132, 217, 137, 32, 49, 48, 48
    str_23_len equ $ - str_23
    str_24 db 32, 32, 216, 167, 217, 132, 217, 134, 216, 170, 217, 138, 216, 172, 216, 169, 58, 32
    str_24_len equ $ - str_24
    str_25 db 
    str_25_len equ $ - str_25
    str_26 db 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144
    str_26_len equ $ - str_26
    str_27 db 240, 159, 147, 138, 32, 216, 175, 217, 133, 216, 172, 32, 216, 167, 217, 132, 217, 134, 216, 170, 216, 167, 216, 166, 216, 172
    str_27_len equ $ - str_27
    str_28 db 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144
    str_28_len equ $ - str_28
    str_29 db 216, 172, 217, 161, 32, 61, 32
    str_29_len equ $ - str_29
    str_30 db 216, 172, 217, 162, 32, 61, 32
    str_30_len equ $ - str_30
    str_31 db 216, 172, 217, 163, 32, 61, 32
    str_31_len equ $ - str_31
    str_32 db 216, 172, 217, 164, 32, 61, 32
    str_32_len equ $ - str_32
    str_33 db 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128, 226, 148, 128
    str_33_len equ $ - str_33
    str_34 db 216, 167, 217, 132, 217, 133, 216, 172, 217, 133, 217, 136, 216, 185, 32, 61, 32
    str_34_len equ $ - str_34
    str_35 db 
    str_35_len equ $ - str_35
    str_36 db 216, 167, 217, 132, 217, 133, 216, 170, 217, 136, 217, 130, 216, 185, 58, 32, 53, 48, 53, 48
    str_36_len equ $ - str_36
    str_37 db 
    str_37_len equ $ - str_37
    str_38 db 226, 156, 133, 32, 216, 167, 217, 132, 217, 134, 216, 170, 216, 167, 216, 166, 216, 172, 32, 217, 133, 216, 170, 216, 183, 216, 167, 216, 168, 217, 130, 216, 169, 33
    str_38_len equ $ - str_38
    str_39 db 226, 157, 140, 32, 216, 174, 216, 183, 216, 163, 32, 217, 129, 217, 138, 32, 216, 167, 217, 132, 216, 173, 216, 179, 216, 167, 216, 168
    str_39_len equ $ - str_39
    str_40 db 
    str_40_len equ $ - str_40
    str_41 db 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144
    str_41_len equ $ - str_41
    str_42 db 226, 156, 133, 32, 216, 167, 217, 131, 216, 170, 217, 133, 217, 132, 32, 217, 133, 216, 171, 216, 167, 217, 132, 32, 216, 167, 217, 132, 216, 172, 217, 133, 216, 185, 32, 216, 167, 217, 132, 217, 133, 216, 170, 217, 136, 216, 167, 216, 178, 217, 138
    str_42_len equ $ - str_42
    str_43 db 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144
    str_43_len equ $ - str_43
    str_44 db 
    str_44_len equ $ - str_44
    str_45 db 217, 133, 216, 178, 216, 167, 217, 138, 216, 167, 32, 216, 167, 217, 132, 216, 170, 217, 136, 216, 167, 216, 178, 217, 138, 58
    str_45_len equ $ - str_45
    str_46 db 226, 128, 162, 32, 216, 179, 216, 177, 216, 185, 216, 169, 32, 216, 163, 216, 185, 217, 132, 217, 137, 32, 40, 52, 32, 216, 174, 217, 138, 217, 136, 216, 183, 32, 226, 137, 136, 32, 52, 195, 151, 32, 216, 163, 216, 179, 216, 177, 216, 185, 41
    str_46_len equ $ - str_46
    str_47 db 226, 128, 162, 32, 216, 167, 216, 179, 216, 170, 216, 186, 217, 132, 216, 167, 217, 132, 32, 216, 163, 217, 129, 216, 182, 217, 132, 32, 217, 132, 217, 132, 217, 133, 216, 185, 216, 167, 217, 132, 216, 172, 216, 167, 216, 170, 32, 217, 133, 216, 170, 216, 185, 216, 175, 216, 175, 216, 169, 32, 216, 167, 217, 132, 217, 134, 217, 136, 217, 137
    str_47_len equ $ - str_47
    str_48 db 226, 128, 162, 32, 217, 130, 216, 167, 216, 168, 217, 132, 217, 138, 216, 169, 32, 216, 167, 217, 132, 216, 170, 217, 136, 216, 179, 216, 185, 32, 217, 133, 216, 185, 32, 216, 173, 216, 172, 217, 133, 32, 216, 167, 217, 132, 216, 168, 217, 138, 216, 167, 217, 134, 216, 167, 216, 170
    str_48_len equ $ - str_48

section .text

arena_alloc:
    push rdi
    mov rax, [arena_ptr]
    test rax, rax
    jnz .arena_init
    mov rax, arena_mem
    mov [arena_ptr], rax
.arena_init:
    mov rdx, rax
    add rdx, rdi
    mov [arena_ptr], rdx
    pop rdi
    ret

print_int:
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    test rax, rax
    jns .pi_pos
    neg rax
    push rax
    mov rax, 1
    mov rdi, 1
    lea rsi, [minus_str]
    mov rdx, 1
    syscall
    pop rax
.pi_pos:
    mov rbx, 10
    mov rcx, 0
    lea rdi, [num_buf + 31]
.piloop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rdi
    mov [rdi], dl
    inc rcx
    test rax, rax
    jnz .piloop
    mov rsi, rdi
    mov byte [rsi + rcx], 10
    inc rcx
    mov rdi, 1
    mov rax, 1
    mov rdx, rcx
    syscall
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    ret

_start:
    mov qword [arena_ptr], 0

    mov rdi, 122
    call arena_alloc
    mov qword [rax], 114
    lea rsi, [str_1]
    lea rdi, [rax + 8]
    mov rcx, 114
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 62
    call arena_alloc
    mov qword [rax], 54
    lea rsi, [str_2]
    lea rdi, [rax + 8]
    mov rcx, 54
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 122
    call arena_alloc
    mov qword [rax], 114
    lea rsi, [str_3]
    lea rdi, [rax + 8]
    mov rcx, 114
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_4]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 47
    call arena_alloc
    mov qword [rax], 39
    lea rsi, [str_5]
    lea rdi, [rax + 8]
    mov rcx, 39
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 34
    call arena_alloc
    mov qword [rax], 26
    lea rsi, [str_6]
    lea rdi, [rax + 8]
    mov rcx, 26
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 0
    mov [vars + 0], rax
    mov rax, 1
    mov [vars + 8], rax
while_start1:
    mov rax, [vars + 8]
    push rax
    mov rax, 100
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true3
    mov rax, 0
    jmp cmp_end4
cmp_true3:
    mov rax, 1
cmp_end4:
    test rax, rax
    jz while_end2
    mov rax, [vars + 0]
    push rax
    mov rax, [vars + 8]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 0], rax
    mov rax, [vars + 8]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 8], rax
    jmp while_start1
while_end2:
    mov rdi, 24
    call arena_alloc
    mov qword [rax], 16
    lea rsi, [str_7]
    lea rdi, [rax + 8]
    mov rcx, 16
    rep movsb
    push rax
    mov rax, [vars + 0]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 28
    call arena_alloc
    mov qword [rax], 20
    lea rsi, [str_8]
    lea rdi, [rax + 8]
    mov rcx, 20
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_9]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 116
    call arena_alloc
    mov qword [rax], 108
    lea rsi, [str_10]
    lea rdi, [rax + 8]
    mov rcx, 108
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 45
    call arena_alloc
    mov qword [rax], 37
    lea rsi, [str_11]
    lea rdi, [rax + 8]
    mov rcx, 37
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 116
    call arena_alloc
    mov qword [rax], 108
    lea rsi, [str_12]
    lea rdi, [rax + 8]
    mov rcx, 108
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_13]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 49
    call arena_alloc
    mov qword [rax], 41
    lea rsi, [str_14]
    lea rdi, [rax + 8]
    mov rcx, 41
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 0
    mov [vars + 16], rax
    mov rax, 1
    mov [vars + 8], rax
while_start5:
    mov rax, [vars + 8]
    push rax
    mov rax, 25
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true7
    mov rax, 0
    jmp cmp_end8
cmp_true7:
    mov rax, 1
cmp_end8:
    test rax, rax
    jz while_end6
    mov rax, [vars + 16]
    push rax
    mov rax, [vars + 8]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 16], rax
    mov rax, [vars + 8]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 8], rax
    jmp while_start5
while_end6:
    mov rdi, 26
    call arena_alloc
    mov qword [rax], 18
    lea rsi, [str_15]
    lea rdi, [rax + 8]
    mov rcx, 18
    rep movsb
    push rax
    mov rax, [vars + 16]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_16]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 50
    call arena_alloc
    mov qword [rax], 42
    lea rsi, [str_17]
    lea rdi, [rax + 8]
    mov rcx, 42
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 0
    mov [vars + 24], rax
    mov rax, 26
    mov [vars + 8], rax
while_start9:
    mov rax, [vars + 8]
    push rax
    mov rax, 50
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true11
    mov rax, 0
    jmp cmp_end12
cmp_true11:
    mov rax, 1
cmp_end12:
    test rax, rax
    jz while_end10
    mov rax, [vars + 24]
    push rax
    mov rax, [vars + 8]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 24], rax
    mov rax, [vars + 8]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 8], rax
    jmp while_start9
while_end10:
    mov rdi, 26
    call arena_alloc
    mov qword [rax], 18
    lea rsi, [str_18]
    lea rdi, [rax + 8]
    mov rcx, 18
    rep movsb
    push rax
    mov rax, [vars + 24]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_19]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 50
    call arena_alloc
    mov qword [rax], 42
    lea rsi, [str_20]
    lea rdi, [rax + 8]
    mov rcx, 42
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 0
    mov [vars + 32], rax
    mov rax, 51
    mov [vars + 8], rax
while_start13:
    mov rax, [vars + 8]
    push rax
    mov rax, 75
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true15
    mov rax, 0
    jmp cmp_end16
cmp_true15:
    mov rax, 1
cmp_end16:
    test rax, rax
    jz while_end14
    mov rax, [vars + 32]
    push rax
    mov rax, [vars + 8]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 32], rax
    mov rax, [vars + 8]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 8], rax
    jmp while_start13
while_end14:
    mov rdi, 26
    call arena_alloc
    mov qword [rax], 18
    lea rsi, [str_21]
    lea rdi, [rax + 8]
    mov rcx, 18
    rep movsb
    push rax
    mov rax, [vars + 32]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_22]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 51
    call arena_alloc
    mov qword [rax], 43
    lea rsi, [str_23]
    lea rdi, [rax + 8]
    mov rcx, 43
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 0
    mov [vars + 40], rax
    mov rax, 76
    mov [vars + 8], rax
while_start17:
    mov rax, [vars + 8]
    push rax
    mov rax, 100
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true19
    mov rax, 0
    jmp cmp_end20
cmp_true19:
    mov rax, 1
cmp_end20:
    test rax, rax
    jz while_end18
    mov rax, [vars + 40]
    push rax
    mov rax, [vars + 8]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 40], rax
    mov rax, [vars + 8]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 8], rax
    jmp while_start17
while_end18:
    mov rdi, 26
    call arena_alloc
    mov qword [rax], 18
    lea rsi, [str_24]
    lea rdi, [rax + 8]
    mov rcx, 18
    rep movsb
    push rax
    mov rax, [vars + 40]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_25]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 116
    call arena_alloc
    mov qword [rax], 108
    lea rsi, [str_26]
    lea rdi, [rax + 8]
    mov rcx, 108
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 34
    call arena_alloc
    mov qword [rax], 26
    lea rsi, [str_27]
    lea rdi, [rax + 8]
    mov rcx, 26
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 116
    call arena_alloc
    mov qword [rax], 108
    lea rsi, [str_28]
    lea rdi, [rax + 8]
    mov rcx, 108
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 16]
    push rax
    mov rax, [vars + 24]
    mov rbx, rax
    pop rax
    add rax, rbx
    push rax
    mov rax, [vars + 32]
    mov rbx, rax
    pop rax
    add rax, rbx
    push rax
    mov rax, [vars + 40]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 48], rax
    mov rdi, 15
    call arena_alloc
    mov qword [rax], 7
    lea rsi, [str_29]
    lea rdi, [rax + 8]
    mov rcx, 7
    rep movsb
    push rax
    mov rax, [vars + 16]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 15
    call arena_alloc
    mov qword [rax], 7
    lea rsi, [str_30]
    lea rdi, [rax + 8]
    mov rcx, 7
    rep movsb
    push rax
    mov rax, [vars + 24]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 15
    call arena_alloc
    mov qword [rax], 7
    lea rsi, [str_31]
    lea rdi, [rax + 8]
    mov rcx, 7
    rep movsb
    push rax
    mov rax, [vars + 32]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 15
    call arena_alloc
    mov qword [rax], 7
    lea rsi, [str_32]
    lea rdi, [rax + 8]
    mov rcx, 7
    rep movsb
    push rax
    mov rax, [vars + 40]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 65
    call arena_alloc
    mov qword [rax], 57
    lea rsi, [str_33]
    lea rdi, [rax + 8]
    mov rcx, 57
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 25
    call arena_alloc
    mov qword [rax], 17
    lea rsi, [str_34]
    lea rdi, [rax + 8]
    mov rcx, 17
    rep movsb
    push rax
    mov rax, [vars + 48]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_35]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 28
    call arena_alloc
    mov qword [rax], 20
    lea rsi, [str_36]
    lea rdi, [rax + 8]
    mov rcx, 20
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 48]
    push rax
    mov rax, [vars + 0]
    mov rbx, rax
    pop rax
    cmp rax, rbx
    je cmp_true21
    mov rax, 0
    jmp cmp_end22
cmp_true21:
    mov rax, 1
cmp_end22:
    mov [vars + 56], rax
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_37]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 56]
    test rax, rax
    jz tern_false23
    mov rdi, 42
    call arena_alloc
    mov qword [rax], 34
    lea rsi, [str_38]
    lea rdi, [rax + 8]
    mov rcx, 34
    rep movsb
    jmp tern_end24
tern_false23:
    mov rdi, 36
    call arena_alloc
    mov qword [rax], 28
    lea rsi, [str_39]
    lea rdi, [rax + 8]
    mov rcx, 28
    rep movsb
tern_end24:
    call print_int
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_40]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 116
    call arena_alloc
    mov qword [rax], 108
    lea rsi, [str_41]
    lea rdi, [rax + 8]
    mov rcx, 108
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 59
    call arena_alloc
    mov qword [rax], 51
    lea rsi, [str_42]
    lea rdi, [rax + 8]
    mov rcx, 51
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 116
    call arena_alloc
    mov qword [rax], 108
    lea rsi, [str_43]
    lea rdi, [rax + 8]
    mov rcx, 108
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_44]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 34
    call arena_alloc
    mov qword [rax], 26
    lea rsi, [str_45]
    lea rdi, [rax + 8]
    mov rcx, 26
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 59
    call arena_alloc
    mov qword [rax], 51
    lea rsi, [str_46]
    lea rdi, [rax + 8]
    mov rcx, 51
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 78
    call arena_alloc
    mov qword [rax], 70
    lea rsi, [str_47]
    lea rdi, [rax + 8]
    mov rcx, 70
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 66
    call arena_alloc
    mov qword [rax], 58
    lea rsi, [str_48]
    lea rdi, [rax + 8]
    mov rcx, 58
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall

    mov rax, 60
    xor rdi, rdi
    syscall
