; ═══════════════════════════════════════════════════
; Generated by Arabic Mathematical Language Compiler
; الدستور: ﴿كتاب أحكمت آياته﴾
; ═══════════════════════════════════════════════════

global _start

section .bss
    arena_ptr resq 1
    arena_mem resb 262144
    file_buf resb 4096
    vars resb 1024
    num_buf resb 32

section .data
    newline db 10
    minus_str db '-'
    str_1 db 53, 33, 32, 61
    str_1_len equ $ - str_1
    str_2 db 217, 129, 217, 138, 216, 168, 217, 136, 217, 134, 216, 167, 216, 170, 216, 180, 217, 138, 58
    str_2_len equ $ - str_2
    str_3 db 217, 133, 216, 172, 217, 133, 217, 136, 216, 185, 32, 49, 32, 216, 165, 217, 132, 217, 137, 32, 49, 48, 48, 58
    str_3_len equ $ - str_3

section .text

arena_alloc:
    push rdi
    mov rax, [arena_ptr]
    test rax, rax
    jnz .arena_init
    mov rax, arena_mem
    mov [arena_ptr], rax
.arena_init:
    mov rdx, rax
    add rdx, rdi
    mov [arena_ptr], rdx
    pop rdi
    ret

print_int:
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    test rax, rax
    jns .pi_pos
    neg rax
    push rax
    mov rax, 1
    mov rdi, 1
    lea rsi, [minus_str]
    mov rdx, 1
    syscall
    pop rax
.pi_pos:
    mov rbx, 10
    mov rcx, 0
    lea rdi, [num_buf + 31]
.piloop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rdi
    mov [rdi], dl
    inc rcx
    test rax, rax
    jnz .piloop
    mov rsi, rdi
    mov byte [rsi + rcx], 10
    inc rcx
    mov rdi, 1
    mov rax, 1
    mov rdx, rcx
    syscall
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    ret

_start:
    mov qword [arena_ptr], 0

    mov rdi, 12
    call arena_alloc
    mov qword [rax], 4
    lea rsi, [str_1]
    lea rdi, [rax + 8]
    mov rcx, 4
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 5
    mov [vars + 0], rax
    mov rax, 1
    mov [vars + 8], rax
    mov rax, 1
    mov [vars + 16], rax
while_start1:
    mov rax, [vars + 16]
    push rax
    mov rax, [vars + 0]
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true3
    mov rax, 0
    jmp cmp_end4
cmp_true3:
    mov rax, 1
cmp_end4:
    test rax, rax
    jz while_end2
    mov rax, [vars + 8]
    push rax
    mov rax, [vars + 16]
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov [vars + 8], rax
    mov rax, [vars + 16]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 16], rax
    jmp while_start1
while_end2:
    mov rax, [vars + 8]
    call print_int
    mov rdi, 27
    call arena_alloc
    mov qword [rax], 19
    lea rsi, [str_2]
    lea rdi, [rax + 8]
    mov rcx, 19
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 0
    mov [vars + 24], rax
    mov rax, 1
    mov [vars + 32], rax
    mov rax, 0
    mov [vars + 16], rax
    mov rax, 10
    mov [vars + 40], rax
while_start5:
    mov rax, [vars + 16]
    push rax
    mov rax, [vars + 40]
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jl cmp_true7
    mov rax, 0
    jmp cmp_end8
cmp_true7:
    mov rax, 1
cmp_end8:
    test rax, rax
    jz while_end6
    mov rax, [vars + 24]
    call print_int
    mov rax, [vars + 24]
    push rax
    mov rax, [vars + 32]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 48], rax
    mov rax, [vars + 32]
    mov [vars + 24], rax
    mov rax, [vars + 48]
    mov [vars + 32], rax
    mov rax, [vars + 16]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 16], rax
    jmp while_start5
while_end6:
    mov rdi, 32
    call arena_alloc
    mov qword [rax], 24
    lea rsi, [str_3]
    lea rdi, [rax + 8]
    mov rcx, 24
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 0
    mov [vars + 56], rax
    mov rax, 1
    mov [vars + 16], rax
while_start9:
    mov rax, [vars + 16]
    push rax
    mov rax, 100
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true11
    mov rax, 0
    jmp cmp_end12
cmp_true11:
    mov rax, 1
cmp_end12:
    test rax, rax
    jz while_end10
    mov rax, [vars + 56]
    push rax
    mov rax, [vars + 16]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 56], rax
    mov rax, [vars + 16]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 16], rax
    jmp while_start9
while_end10:
    mov rax, [vars + 56]
    call print_int

    mov rax, 60
    xor rdi, rdi
    syscall
