; ═══════════════════════════════════════════════════
; Generated by Arabic Mathematical Language Compiler
; الدستور: ﴿كتاب أحكمت آياته﴾
; ═══════════════════════════════════════════════════

global _start

section .bss
    arena_ptr resq 1
    arena_mem resb 262144
    file_buf resb 4096
    vars resb 1024
    num_buf resb 32

section .data
    newline db 10
    minus_str db '-'
    str_1 db 226, 149, 148, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 151
    str_1_len equ $ - str_1
    str_2 db 226, 149, 145, 32, 32, 32, 216, 167, 217, 132, 216, 168, 216, 177, 217, 133, 216, 172, 216, 169, 32, 216, 167, 217, 132, 217, 133, 216, 170, 217, 136, 216, 167, 216, 178, 217, 138, 216, 169, 32, 45, 32, 216, 167, 217, 132, 216, 163, 216, 179, 216, 167, 216, 179, 217, 138, 216, 167, 216, 170, 32, 32, 32, 32, 226, 149, 145
    str_2_len equ $ - str_2
    str_3 db 226, 149, 154, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 157
    str_3_len equ $ - str_3
    str_4 db 
    str_4_len equ $ - str_4
    str_5 db 240, 159, 147, 141, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 49, 32, 217, 138, 216, 168, 216, 175, 216, 163, 46, 46, 46
    str_5_len equ $ - str_5
    str_6 db 32, 32, 91, 216, 174, 217, 138, 216, 183, 32, 49, 93, 32, 216, 185, 32, 61, 32
    str_6_len equ $ - str_6
    str_7 db 226, 156, 147, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 49, 32, 216, 167, 217, 134, 216, 170, 217, 135, 217, 137
    str_7_len equ $ - str_7
    str_8 db 
    str_8_len equ $ - str_8
    str_9 db 240, 159, 147, 141, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 50, 32, 217, 138, 216, 168, 216, 175, 216, 163, 46, 46, 46
    str_9_len equ $ - str_9
    str_10 db 32, 32, 91, 216, 174, 217, 138, 216, 183, 32, 50, 93, 32, 216, 185, 32, 61, 32
    str_10_len equ $ - str_10
    str_11 db 226, 156, 147, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 50, 32, 216, 167, 217, 134, 216, 170, 217, 135, 217, 137
    str_11_len equ $ - str_11
    str_12 db 
    str_12_len equ $ - str_12
    str_13 db 240, 159, 147, 141, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 51, 32, 217, 138, 216, 168, 216, 175, 216, 163, 32, 40, 216, 173, 216, 179, 216, 167, 216, 168, 32, 54, 33, 41, 46, 46, 46
    str_13_len equ $ - str_13
    str_14 db 32, 32, 91, 216, 174, 217, 138, 216, 183, 32, 51, 93, 32, 54, 33, 32, 61, 32
    str_14_len equ $ - str_14
    str_15 db 226, 156, 147, 32, 216, 167, 217, 132, 216, 174, 217, 138, 216, 183, 32, 51, 32, 216, 167, 217, 134, 216, 170, 217, 135, 217, 137
    str_15_len equ $ - str_15
    str_16 db 
    str_16_len equ $ - str_16
    str_17 db 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144
    str_17_len equ $ - str_17
    str_18 db 226, 156, 133, 32, 216, 172, 217, 133, 217, 138, 216, 185, 32, 216, 167, 217, 132, 216, 174, 217, 138, 217, 136, 216, 183, 32, 216, 167, 217, 134, 216, 170, 217, 135, 216, 170, 32, 216, 168, 217, 134, 216, 172, 216, 167, 216, 173
    str_18_len equ $ - str_18
    str_19 db 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144, 226, 149, 144
    str_19_len equ $ - str_19
    str_20 db 
    str_20_len equ $ - str_20
    str_21 db 217, 133, 217, 132, 216, 167, 216, 173, 216, 184, 216, 169, 58, 32, 217, 135, 216, 176, 216, 167, 32, 216, 167, 217, 132, 217, 133, 216, 171, 216, 167, 217, 132, 32, 217, 138, 217, 143, 216, 184, 217, 135, 216, 177, 32, 216, 167, 217, 132, 217, 133, 216, 173, 216, 167, 217, 131, 216, 167, 216, 169, 46
    str_21_len equ $ - str_21
    str_22 db 216, 167, 217, 132, 216, 170, 217, 136, 216, 167, 216, 178, 217, 138, 32, 216, 167, 217, 132, 217, 129, 216, 185, 217, 132, 217, 138, 32, 217, 138, 216, 170, 216, 183, 217, 132, 216, 168, 32, 216, 167, 217, 131, 216, 170, 217, 133, 216, 167, 217, 132, 32, 216, 167, 217, 132, 217, 133, 216, 177, 216, 173, 217, 132, 216, 169, 32, 52, 49, 46
    str_22_len equ $ - str_22

section .text

arena_alloc:
    push rdi
    mov rax, [arena_ptr]
    test rax, rax
    jnz .arena_init
    mov rax, arena_mem
    mov [arena_ptr], rax
.arena_init:
    mov rdx, rax
    add rdx, rdi
    mov [arena_ptr], rdx
    pop rdi
    ret

print_int:
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    test rax, rax
    jns .pi_pos
    neg rax
    push rax
    mov rax, 1
    mov rdi, 1
    lea rsi, [minus_str]
    mov rdx, 1
    syscall
    pop rax
.pi_pos:
    mov rbx, 10
    mov rcx, 0
    lea rdi, [num_buf + 31]
.piloop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rdi
    mov [rdi], dl
    inc rcx
    test rax, rax
    jnz .piloop
    mov rsi, rdi
    mov byte [rsi + rcx], 10
    inc rcx
    mov rdi, 1
    mov rax, 1
    mov rdx, rcx
    syscall
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    ret

_start:
    mov qword [arena_ptr], 0

    mov rdi, 122
    call arena_alloc
    mov qword [rax], 114
    lea rsi, [str_1]
    lea rdi, [rax + 8]
    mov rcx, 114
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 75
    call arena_alloc
    mov qword [rax], 67
    lea rsi, [str_2]
    lea rdi, [rax + 8]
    mov rcx, 67
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 122
    call arena_alloc
    mov qword [rax], 114
    lea rsi, [str_3]
    lea rdi, [rax + 8]
    mov rcx, 114
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_4]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 37
    call arena_alloc
    mov qword [rax], 29
    lea rsi, [str_5]
    lea rdi, [rax + 8]
    mov rcx, 29
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 1
    mov [vars + 0], rax
while_start1:
    mov rax, [vars + 0]
    push rax
    mov rax, 5
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true3
    mov rax, 0
    jmp cmp_end4
cmp_true3:
    mov rax, 1
cmp_end4:
    test rax, rax
    jz while_end2
    mov rdi, 26
    call arena_alloc
    mov qword [rax], 18
    lea rsi, [str_6]
    lea rdi, [rax + 8]
    mov rcx, 18
    rep movsb
    push rax
    mov rax, [vars + 0]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 0]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 0], rax
    jmp while_start1
while_end2:
    mov rdi, 35
    call arena_alloc
    mov qword [rax], 27
    lea rsi, [str_7]
    lea rdi, [rax + 8]
    mov rcx, 27
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_8]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 37
    call arena_alloc
    mov qword [rax], 29
    lea rsi, [str_9]
    lea rdi, [rax + 8]
    mov rcx, 29
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 10
    mov [vars + 8], rax
while_start5:
    mov rax, [vars + 8]
    push rax
    mov rax, 15
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true7
    mov rax, 0
    jmp cmp_end8
cmp_true7:
    mov rax, 1
cmp_end8:
    test rax, rax
    jz while_end6
    mov rdi, 26
    call arena_alloc
    mov qword [rax], 18
    lea rsi, [str_10]
    lea rdi, [rax + 8]
    mov rcx, 18
    rep movsb
    push rax
    mov rax, [vars + 8]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, [vars + 8]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 8], rax
    jmp while_start5
while_end6:
    mov rdi, 35
    call arena_alloc
    mov qword [rax], 27
    lea rsi, [str_11]
    lea rdi, [rax + 8]
    mov rcx, 27
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_12]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 51
    call arena_alloc
    mov qword [rax], 43
    lea rsi, [str_13]
    lea rdi, [rax + 8]
    mov rcx, 43
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rax, 6
    mov [vars + 16], rax
    mov rax, 1
    mov [vars + 24], rax
    mov rax, 1
    mov [vars + 32], rax
while_start9:
    mov rax, [vars + 32]
    push rax
    mov rax, [vars + 16]
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true11
    mov rax, 0
    jmp cmp_end12
cmp_true11:
    mov rax, 1
cmp_end12:
    test rax, rax
    jz while_end10
    mov rax, [vars + 24]
    push rax
    mov rax, [vars + 32]
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov [vars + 24], rax
    mov rax, [vars + 32]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 32], rax
    jmp while_start9
while_end10:
    mov rdi, 26
    call arena_alloc
    mov qword [rax], 18
    lea rsi, [str_14]
    lea rdi, [rax + 8]
    mov rcx, 18
    rep movsb
    push rax
    mov rax, [vars + 24]
    mov rdi, rax
    call int_to_str
    mov rbx, rax
    pop rax
    push rax
    push rbx
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    add rcx, 8
    mov rdi, rcx
    call arena_alloc
    mov r8, rax
    pop rbx
    pop rax
    mov rcx, [rax]
    mov rdx, [rbx]
    add rcx, rdx
    mov [r8], rcx
    mov rcx, [rax]
    lea rsi, [rax + 8]
    lea rdi, [r8 + 8]
    rep movsb
    mov rcx, [rbx]
    lea rsi, [rbx + 8]
    rep movsb
    mov rax, r8
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 35
    call arena_alloc
    mov qword [rax], 27
    lea rsi, [str_15]
    lea rdi, [rax + 8]
    mov rcx, 27
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_16]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 116
    call arena_alloc
    mov qword [rax], 108
    lea rsi, [str_17]
    lea rdi, [rax + 8]
    mov rcx, 108
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 55
    call arena_alloc
    mov qword [rax], 47
    lea rsi, [str_18]
    lea rdi, [rax + 8]
    mov rcx, 47
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 116
    call arena_alloc
    mov qword [rax], 108
    lea rsi, [str_19]
    lea rdi, [rax + 8]
    mov rcx, 108
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 8
    call arena_alloc
    mov qword [rax], 0
    lea rsi, [str_20]
    lea rdi, [rax + 8]
    mov rcx, 0
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 70
    call arena_alloc
    mov qword [rax], 62
    lea rsi, [str_21]
    lea rdi, [rax + 8]
    mov rcx, 62
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall
    mov rdi, 78
    call arena_alloc
    mov qword [rax], 70
    lea rsi, [str_22]
    lea rdi, [rax + 8]
    mov rcx, 70
    rep movsb
    mov rdx, [rax]
    lea rsi, [rax + 8]
    mov rdi, 1
    mov rax, 1
    syscall
    mov rdi, 1
    lea rsi, [newline]
    mov rdx, 1
    mov rax, 1
    syscall

    mov rax, 60
    xor rdi, rdi
    syscall
