; ═══════════════════════════════════════════════════
; Generated by Arabic Mathematical Language Compiler
; الدستور: ﴿كتاب أحكمت آياته﴾
; ═══════════════════════════════════════════════════

global _start

section .bss
    arena_ptr resq 1
    arena_mem resb 262144
    file_buf resb 4096
    vars resb 1024
    num_buf resb 32

section .data
    newline db 10
    minus_str db '-'

section .text

arena_alloc:
    push rdi
    mov rax, [arena_ptr]
    test rax, rax
    jnz .arena_init
    mov rax, arena_mem
    mov [arena_ptr], rax
.arena_init:
    mov rdx, rax
    add rdx, rdi
    mov [arena_ptr], rdx
    pop rdi
    ret

print_int:
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    test rax, rax
    jns .pi_pos
    neg rax
    push rax
    mov rax, 1
    mov rdi, 1
    lea rsi, [minus_str]
    mov rdx, 1
    syscall
    pop rax
.pi_pos:
    mov rbx, 10
    mov rcx, 0
    lea rdi, [num_buf + 31]
.piloop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rdi
    mov [rdi], dl
    inc rcx
    test rax, rax
    jnz .piloop
    mov rsi, rdi
    mov byte [rsi + rcx], 10
    inc rcx
    mov rdi, 1
    mov rax, 1
    mov rdx, rcx
    syscall
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    ret

_start:
    mov qword [arena_ptr], 0

    mov rax, 1
    call print_int
    mov rax, 2
    call print_int
    mov rax, 3
    call print_int
    mov rax, 4
    call print_int
    mov rax, 5
    call print_int
    mov rax, 0
    mov [vars + 0], rax
while_start1:
    mov rax, [vars + 0]
    push rax
    mov rax, 10
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jl cmp_true3
    mov rax, 0
    jmp cmp_end4
cmp_true3:
    mov rax, 1
cmp_end4:
    test rax, rax
    jz while_end2
    mov rax, [vars + 0]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 0], rax
    jmp while_start1
while_end2:
    mov rax, [vars + 0]
    call print_int
    mov rax, 0
    mov [vars + 8], rax
    mov rax, 1
    mov [vars + 0], rax
while_start5:
    mov rax, [vars + 0]
    push rax
    mov rax, 100
    mov rbx, rax
    pop rax
    cmp rax, rbx
    jle cmp_true7
    mov rax, 0
    jmp cmp_end8
cmp_true7:
    mov rax, 1
cmp_end8:
    test rax, rax
    jz while_end6
    mov rax, [vars + 8]
    push rax
    mov rax, [vars + 0]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 8], rax
    mov rax, [vars + 0]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [vars + 0], rax
    jmp while_start5
while_end6:
    mov rax, [vars + 8]
    call print_int

    mov rax, 60
    xor rdi, rdi
    syscall
