#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
المرحلة 5: مُجمّع يدعم أرقام متعددة الخانات — مكتوب بلغتنا العربية
"""
import sys, subprocess
sys.path.insert(0, '.')
from math_complete import *

برنامج_مولد_v2 = """مصدر ≔ ⊙
طول_م ≔ حجم(مصدر)
موضع ≔ 4
أ ≔ 0
م ≔ 1
μ م = 1 : ﴿ حرف ≔ رمز(مصدر، موضع) ⋄ م ≔ حرف ≠ 32 ⋄ أ ≔ م ؟ أ · 10 + حرف - 48 : أ ⋄ موضع ≔ م ؟ موضع + 1 : موضع ﴾
عملية ≔ رمز(مصدر، موضع + 1)
موضع ≔ موضع + 3
ب ≔ 0
م ≔ 1
μ م = 1 : ﴿ م ≔ موضع < طول_م ⋄ حرف ≔ م ؟ رمز(مصدر، موضع) : 32 ⋄ ب ≔ م ؟ ب · 10 + حرف - 48 : ب ⋄ موضع ≔ م ؟ موضع + 1 : موضع ﴾
عملية_نص ≔ "add rax, rbx"
م ≔ عملية = 45
عملية_نص ≔ م ؟ "sub rax, rbx" : عملية_نص
م ≔ عملية = 42
عملية_نص ≔ م ؟ "imul rax, rbx" : عملية_نص
⎕ "; Generated by Arabic Math Compiler v2"
⎕ "mov rax, " ⊕ نص(أ)
⎕ "mov rbx, " ⊕ نص(ب)
⎕ عملية_نص
⎕ "; result in rax"
"""

print("=" * 50)
print("المرحلة 5: أرقام متعددة الخانات")
print("=" * 50)
print("\n📝 البرنامج (بلغتنا العربية):")
print(برنامج_مولد_v2)
print("🔧 التجميع...")
ر = حلل_رموز(برنامج_مولد_v2)
ب = حلل_برنامج(ر)
asm = compile_program(ب)
with open('gen2.asm', 'w', encoding='utf-8') as f:
    f.write(asm)
subprocess.run(['nasm', '-f', 'elf64', 'gen2.asm', '-o', 'gen2.o'], check=True)
subprocess.run(['ld', 'gen2.o', '-o', 'gen2'], check=True)
print("✅ تم تجميع المولّد v2")

print("\n🧪 الاختبارات:")
tests = [
    ("⎕ 12 + 34", ["mov rax, 12", "mov rbx, 34", "add rax, rbx"]),
    ("⎕ 9 - 4", ["mov rax, 9", "mov rbx, 4", "sub rax, rbx"]),
    ("⎕ 3 * 7", ["mov rax, 3", "mov rbx, 7", "imul rax, rbx"]),
    ("⎕ 100 + 200", ["mov rax, 100", "mov rbx, 200", "add rax, rbx"]),
    ("⎕ 50 - 25", ["mov rax, 50", "mov rbx, 25", "sub rax, rbx"]),
]
failed = 0
for inp, expected_lines in tests:
    result = subprocess.run(['./gen2'], capture_output=True, text=True, input=inp + "\n")
    out = result.stdout.strip()
    all_found = all(line in out for line in expected_lines)
    if all_found:
        print(f"  ✅ {inp}")
    else:
        print(f"  ❌ {inp}")
        print(f"     الخرج: {out}")
        failed += 1

print("\n" + "=" * 50)
if failed == 0:
    print(f"🎉 المرحلة 5 نجحت! ({len(tests)}/{len(tests)})")
    print("لغتنا تدعم أرقام متعددة الخانات + حلقة parse!")
else:
    print(f"❌ فشل {failed} اختبار")
    sys.exit(1)
