#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
المرحلة 4: مُجمّع يولّد Assembly — مكتوب بلغتنا العربية
"""
import sys, subprocess
sys.path.insert(0, '.')
from math_complete import *

برنامج_مولد = """مصدر ≔ ⊙
أ ≔ رمز(مصدر، 4) - 48
عملية ≔ رمز(مصدر، 6)
ب ≔ رمز(مصدر، 8) - 48
عملية_نص ≔ "add rax, rbx"
م ≔ عملية = 45
عملية_نص ≔ م ؟ "sub rax, rbx" : عملية_نص
م ≔ عملية = 42
عملية_نص ≔ م ؟ "imul rax, rbx" : عملية_نص
⎕ "; Generated by Arabic Math Compiler"
⎕ "mov rax, " ⊕ نص(أ)
⎕ "mov rbx, " ⊕ نص(ب)
⎕ عملية_نص
⎕ "; result in rax"
"""

print("=" * 50)
print("المرحلة 4: مُجمّع يولّد Assembly")
print("=" * 50)
print("\n📝 البرنامج (بلغتنا العربية):")
print(برنامج_مولد)
print("🔧 التجميع...")
ر = حلل_رموز(برنامج_مولد)
ب = حلل_برنامج(ر)
asm = compile_program(ب)
with open('gen.asm', 'w', encoding='utf-8') as f:
    f.write(asm)
subprocess.run(['nasm', '-f', 'elf64', 'gen.asm', '-o', 'gen.o'], check=True)
subprocess.run(['ld', 'gen.o', '-o', 'gen'], check=True)
print("✅ تم تجميع المولّد")

print("\n🧪 الاختبارات:")
tests = [
    ("⎕ 2 + 3", ["mov rax, 2", "mov rbx, 3", "add rax, rbx"]),
    ("⎕ 9 - 4", ["mov rax, 9", "mov rbx, 4", "sub rax, rbx"]),
    ("⎕ 3 * 7", ["mov rax, 3", "mov rbx, 7", "imul rax, rbx"]),
    ("⎕ 5 + 5", ["mov rax, 5", "mov rbx, 5", "add rax, rbx"]),
]
failed = 0
for inp, expected_lines in tests:
    result = subprocess.run(['./gen'], capture_output=True, text=True, input=inp + "\n")
    out = result.stdout.strip()
    all_found = all(line in out for line in expected_lines)
    if all_found:
        print(f"  ✅ {inp}")
        print("     المخرج:")
        for line in out.split('\n'):
            print(f"       {line}")
    else:
        print(f"  ❌ {inp}")
        print(f"     الخرج: {out}")
        failed += 1
print("\n" + "=" * 50)
if failed == 0:
    print(f"🎉 المرحلة 4 نجحت! ({len(tests)}/{len(tests)})")
    print("لغتنا العربية تولّد Assembly حقيقي!")
else:
    print(f"❌ فشل {failed} اختبار")
    sys.exit(1)
